// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1zfD8Xb9wgVsFL4NEat9mNUgSiv-TVSE',
    appId: '1:899432780815:web:b5ca4b763e3f221e243f7a',
    messagingSenderId: '899432780815',
    projectId: 'check-list-app-d0a37',
    authDomain: 'check-list-app-d0a37.firebaseapp.com',
    databaseURL: 'https://check-list-app-d0a37-default-rtdb.firebaseio.com',
    storageBucket: 'check-list-app-d0a37.appspot.com',
    measurementId: 'G-040P0SHR5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVATtXeiEtDk7LsRNuliZz2pSiilEZHK0',
    appId: '1:899432780815:android:aad44d6039ef3ac7243f7a',
    messagingSenderId: '899432780815',
    projectId: 'check-list-app-d0a37',
    databaseURL: 'https://check-list-app-d0a37-default-rtdb.firebaseio.com',
    storageBucket: 'check-list-app-d0a37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMGOu9A3hN_1G_V7LnQDBp9nGW5qn2tpQ',
    appId: '1:899432780815:ios:f4d56be2edda4b0b243f7a',
    messagingSenderId: '899432780815',
    projectId: 'check-list-app-d0a37',
    databaseURL: 'https://check-list-app-d0a37-default-rtdb.firebaseio.com',
    storageBucket: 'check-list-app-d0a37.appspot.com',
    iosBundleId: 'com.example.checklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMGOu9A3hN_1G_V7LnQDBp9nGW5qn2tpQ',
    appId: '1:899432780815:ios:5537d4f7eb3a573c243f7a',
    messagingSenderId: '899432780815',
    projectId: 'check-list-app-d0a37',
    databaseURL: 'https://check-list-app-d0a37-default-rtdb.firebaseio.com',
    storageBucket: 'check-list-app-d0a37.appspot.com',
    iosBundleId: 'com.example.checklist.RunnerTests',
  );
}
